### ISSUE TITLE
Documentation in english 

### ISSUE THREAD

**Issue by artras** [Netural/php-browser-language#1]
A good code ,tnx!  It will be nice, if documentation will be in English :)

**Comment by DominikAngerer** [comment]
Hello artras - comments are now in English :) hope it helps you out.

**Comment by artras** [comment]
Tnx, I use your script in my framework...

**Comment by ddprrt** [comment]
Pretty sweet! Glad that it helps not only the guys at Netural

**Comment by artras** [comment]
Netural?

**Comment by ddprrt** [comment]
Netural is the company I originally created the script for: http://netural.com

**Comment by artras** [comment]
Oh, tnx you to :) Good luck!
